// ─────────────────────────────────────────────────────────────
// Domain types for Grace Furniture.
// Kept at types/menu.ts so existing imports across the codebase
// don't need to change. `MenuItem` is aliased to `Product` for
// the same reason — the customer-facing pages read better as
// "Product" but the admin code still references MenuItem.
// ─────────────────────────────────────────────────────────────

export type CategoryIcon =
  | "sofas"
  | "chairs"
  | "tables"
  | "desks"
  | "beds"
  | "storage"
  | "lighting";

export interface Category {
  id: string;
  name: string;
  order: number;
  icon: CategoryIcon;
}

/** A furniture piece in the catalog. */
export interface Product {
  id: string;
  categoryId: string;
  name: string;
  /** Headline price in USD. */
  price: number;
  /** One-line marketing line shown under the name. */
  tagline: string;
  /** Long-form editorial copy on the product page. */
  description: string;

  /** Hero image (WebP recommended for production). */
  imageUrl: string;
  /** Optional secondary images for the gallery. */
  galleryUrls?: string[];

  /** GLB for Android / desktop / WebXR. Optional — items without a model hide the AR CTA. */
  modelUrl?: string;
  /** USDZ for iOS Quick Look. */
  usdzUrl?: string;

  /** Real-world dimensions in centimetres. */
  dimensions: {
    width: number;
    depth: number;
    height: number;
  };
  /** Materials, e.g. ["Solid Oak", "Brass", "Bouclé"]. */
  materials: string[];
  /** Style/design movement, e.g. "Modern", "Brutalist", "Mid-century". */
  style: ProductStyle;

  /** Editor's pick — drives the recommend ribbon. */
  isBestseller?: boolean;
  /** Coming-soon flag — disables Add-to-Cart. */
  isComingSoon?: boolean;
  /** Stock count for the urgency badge. 0 = out of stock. */
  stock?: number;
}

export type ProductStyle =
  | "Modern"
  | "Mid-century"
  | "Brutalist"
  | "Classic"
  | "Industrial"
  | "Japandi";

/** Back-compat alias so admin code that imports MenuItem still works. */
export type MenuItem = Product;

/** Editorial styling note generated by Gemini. */
export interface StylingNote {
  /** 2-line interior-stylist description. */
  description: string;
  /** Short pairing suggestion (room, complementary piece). */
  roomFit?: string;
  /** Quick-glance material/style tags. */
  highlights?: string[];
}

/** Back-compat alias used by useGeminiInsights & AIInsights. */
export type TastingNote = StylingNote;
